### ISSUE TITLE
Duplicate table created (throws already exists error)

### ISSUE THREAD

**Issue by ghost** [OrdnanceSurvey/AddressBase#2]
In the SQL table creation script for AddressBase Premium, (PostgreSQL_AddressBase_Premium_CreateTable.sql), `CREATE TABLE abp_street` is listed twice. This stops the query as it detects table trying to be created twice, therefore 'table already exist'.
Both abp_street tables have different structure, the second in the script being the correct one (as column names match up with column names in the CSVs).

**Comment by AMcCluneOS** [comment]
Thanks for your feedback. This has now been corrected!
